### ISSUE TITLE
Wrongly truncating numbers

### ISSUE THREAD

**Issue by mateusmedeiros** [pythonicrubyist/creek#21] opened 2015-11-09 00:07 UTC
I'm not sure if this is a bug of Google Sheets or Creek (or both or neither), but I have a spreadsheet with a row filled with numbers. One of these numbers, for example, is displayed on google sheets as `52.097.260`. Up in the "fx" bar, the same number is displayed as `52097260`.

In the sheet xml it seems the number is actually a float: `<v>5.209726E7</v>`. Ok until here.

When I try to get the rows with Creek in my ruby app though, the row is returned like this:
```ruby
{"A5"=>"Brasil", "B5"=>5, "C5"=>5, "D5"=>5, "E5"=>5, "F5"=>5, "G5"=>5, "H5"=>5, "I5"=>5, "J5"=>5, "K5"=>5, "L5"=>8, "M5"=>8, "N5"=>8, "O5"=>8, "P5"=>8, "Q5"=>8, "R5"=>8, "S5"=>8, "T5"=>8, "U5"=>8, "V5"=>8, "W5"=>1, "X5"=>1, "Y5"=>1, "Z5"=>1, "AA5"=>1, "AB5"=>1, "AC5"=>1, "AD5"=>1, "AE5"=>1, "AF5"=>1, "AG5"=>1, "AH5"=>1, "AI5"=>1, "AJ5"=>1, "AK5"=>1, "AL5"=>1, "AM5"=>1, "AN5"=>1, "AO5"=>1, "AP5"=>1, "AQ5"=>1, "AR5"=>1, "AS5"=>nil, "AT5"=>nil, "AU5"=>nil, "AV5"=>nil, "AW5"=>nil, "AX5"=>nil, "AY5"=>nil, "AZ5"=>nil, "BA5"=>nil, "BB5"=>nil, "BC5"=>nil}
```

From what I could tell by reading creek's source code, it is something related to styles. 
The style of the numbers of these rows is either "38" or "39". Here are they on the `styles.xml`:

```xml
<xf borderId="10" fillId="0" fontId="1" numFmtId="3" xfId="0" applyBorder="1" applyFont="1" applyNumberFormat="1"/>
<xf borderId="11" fillId="0" fontId="1" numFmtId="3" xfId="0" applyBorder="1" applyFont="1" applyNumberFormat="1"/>
```

Both have `numFmtId="3"`, which is for fixnum, according to https://github.com/pythonicrubyist/creek/blob/ff478caee306774ffd7423d46a7502027277ffa3/lib/creek/styles/constants.rb.

I tried to edit the `styles.xml` directly just to test that out, changing both styles to have `numFmtId="0"`. 

The resulting hash changed to:
```ruby
{"A5"=>"Brasil", "B5"=>"5.209726E7", "C5"=>"5.21612016E7", "D5"=>"5.22251432E7", "E5"=>"5.22890848E7", "F5"=>"5.235302640000001E7", "G5"=>"5.241696800000001E7", "H5"=>"5.248090960000001E7", "I5"=>"5.254485120000001E7", "J5"=>"5.260879280000001E7", "K5"=>"5.267273440000001E7", "L5"=>"8.0437327E7", "M5"=>"8.047588936363636E7", "N5"=>"8.051445172727272E7", "O5"=>"8.055301409090908E7", "P5"=>"8.059157645454544E7", "Q5"=>"8.06301388181818E7", "R5"=>"8.066870118181816E7", "S5"=>"8.070726354545452E7", "T5"=>"8.074582590909088E7", "U5"=>"8.078438827272724E7", "V5"=>"8.08229506363636E7", "W5"=>"1.1099099E8", "X5"=>"1.139836842222222E8", "Y5"=>"1.169763784444444E8", "Z5"=>"1.199690726666667E8", "AA5"=>"1.229617668888889E8", "AB5"=>"1.259544611111111E8", "AC5"=>"1.289471553333333E8", "AD5"=>"1.319398495555556E8", "AE5"=>"1.349325437777778E8", "AF5"=>"1.37925238E8", "AG5"=>"1.402261791E8", "AH5"=>"1.425271202E8", "AI5"=>"1.448280613E8", "AJ5"=>"1.471290024E8", "AK5"=>"1.494299435E8", "AL5"=>"1.517308846E8", "AM5"=>"1.540318257E8", "AN5"=>"1.563327668E8", "AO5"=>"1.586337078999999E8", "AP5"=>"1.60934649E8", "AQ5"=>"1.632355901E8", "AR5"=>"1.655365312E8", "AS5"=>nil, "AT5"=>nil, "AU5"=>nil, "AV5"=>nil, "AW5"=>nil, "AX5"=>nil, "AY5"=>nil, "AZ5"=>nil, "BA5"=>nil, "BB5"=>nil, "BC5"=>nil}
```

Which I guess is expected, considering that with numFmtId 0 creek just returns the value.

So, my conclusion was that the styles associated with those cells should have a float numFmtId. 

Now, I'm not quite sure if it's creek's fault or if the sheets Google Sheets make are ill-formed. If creek got the values right and the sheets are actually wrong, then please just close this issue.

I made a gist with the offending file before and after I changed the `styles.xml`, and also both `styles.xml` and a diff of them showing that the only change I made was in the numFmtIds.

https://gist.github.com/mateusmedeiros/47ec1f4ce704f4c85729
The "working" files are what I got after I changed the numFmtId, the "broken" are before the change.

**Comment by pythonicrubyist** [comment] 2016-01-07 19:02
I'm not able to reproduce this error. I tried it on a few sample files that I have and I don't see Creek rounding up floats.

**Comment by mateusmedeiros** [comment] 2016-01-07 19:29
Did you try with the ones on the gist? I'm not well-versed on the internals of the xlsx format, so I don't know if it's really a bug on creek or in the tool that made the xlsx (google docs). LibreOffice will also display the number correctly, though (`52.097.260`).

**Comment by tostasqb** [comment] 2016-01-18 13:16
I have this problem also. 
Example. I have a cell with the value 2.16 that is formatted as as number with no decimal places. Creek reads 2.

![image](http://s12.postimg.org/qir9nwf7x/Screen_Shot_2016_01_18_at_13_10_45.png)

**Comment by tostasqb** [comment] 2016-01-18 13:27
Reading it better I guess my issue is not related to this one, opened a new one (#23). Sorry the spam here guys.

**Comment by pythonicrubyist** [comment] 2016-04-21 19:02
@mateusmedeiros The whole process of parsing of numbers is being redone in the next version of creek(2.0) which will be released soon. That should solve this issue.

**Closed by pythonicrubyist** 2016-04-21 19:02 UTC
